### ISSUE TITLE
Getting Started not working

### ISSUE THREAD

**Issue by derJake** [Malvid/Malvid#67] opened 2020-04-14 12:39 UTC
**Description**

Hi, I've been following the instructions in the [Malvid/docs/Get started.md][getstarted] but I either get a 404 or invalid response from server error.

**How to reproduce**
Follow the steps in the [Get started.md][getstarted] of the current master up until 
```shell_script
npx http-serve ./src -c-1
```

Click one of the provided server links in the terminal or open the index.html directly.

**Expected behaviour**
Seeing a Malvid frontend displaying the sidebar, template code and preview window with the button component.

**Observed behaviour**
When clicking one of the provided links for the ad-hoc server, Chrome fails with an `ERR_INVALID_REDIRECT` error message.

When opening the index.html directly, instead of the component preview, there is a 404 page.

[getstarted]: <https://github.com/Malvid/Malvid/blob/master/docs/Get%20started.md>

**Comment by electerious** [comment] 2020-04-14 14:55
Could you try it with [this repo](https://github.com/Malvid/get-started)? It contains the same files you create during the "get started"-guide and works fine for me.

```
git clone https://github.com/Malvid/get-started.git
cd get-started
npx http-serve ./src -c-1
```

**Comment by derJake** [comment] 2020-04-14 18:59
Hey @electerious 
Unfortunately I get the same error there. I'm using npm 6.4.14 on node 12.16.2 running on Windows 10 Pro Version	10.0.18362 Build 18362
Maybe this is a windows only issue?

**Comment by electerious** [comment] 2020-04-19 17:48
It could be a windows issue. Maybe it's just the wrong path and you must use a backsplash on windows?

```
npx http-serve .\src -c-1
```

**Comment by derJake** [comment] 2020-04-20 06:59
Unfortunately it seems to persist even with a backslash. Then again, shouldn't the index.html be saying something else than "Couldn't fetch" anyway?

**Comment by electerious** [comment] 2020-09-04 15:50
I'm closing this issue as I'm not able to reproduce it.

**Closed by electerious** 2020-09-04 15:50 UTC
